columns:
  age: int64
  workclass: object
  fnlwgt: int64
  education: object
  education-num: int64
  marital-status: object
  occupation: object
  relationship: object
  race: object
  sex: object
  capital-gain: int64
  capital-loss: int64
  hours-per-week: int64
  native-country: object
  income: object

numerical_columns:        
  - age
  - fnlwgt
  - education-num
  - capital-gain
  - capital-loss
  - hours-per-week

categorical_columns:
  - workclass
  - education
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - native-country
  - income

target_column : income